version: "3.8"

services:
  mongodb:
    image: mongo:5.0.2
    restart: unless-stopped
   
    volumes:
      - db:/data/db
  app:
    depends_on:
      - mongodb
    build: ./
    restart: unless-stopped

    ports:
      - 6868:8080

    stdin_open: true
    tty: true

volumes:
  db:
